name: Build and Push n8n Docker Image

on:
  push:
    branches:
      - replikate

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Set n8n version and release date
        id: set-version
        run: |
          echo "N8N_VERSION=1.81.0" >> $GITHUB_ENV
          echo "NODE_VERSION=22" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Build n8n image
        run: |
          cd ./docker/images/n8n
          docker build -t registry.digitalocean.com/replikate-sg/n8n:${{ env.SHORT_SHA }} \
            --build-arg NODE_VERSION=${{ env.NODE_VERSION }} \
            --build-arg N8N_VERSION=${{ env.N8N_VERSION }} \
            --build-arg N8N_RELEASE_DATE=${{ env.RELEASE_DATE }} \
            .

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/replikate-sg/n8n:${{ env.SHORT_SHA }}
