name: Build and Push n8n Docker Image

on:
  push:
    branches: [ replikate ]
  workflow_dispatch:
    inputs:
      n8n_version:
        description: 'n8n version to build'
        required: false
        default: '1.81.0'
      node_version:
        description: 'Node.js version to use'
        required: false
        default: '22'

jobs:
  build-base:
    uses: ./.github/workflows/docker-base-image-do.yml
    with:
      node_version: ${{ github.event.inputs.node_version || '20' }}
    secrets: inherit

  build-and-push:
    needs: build-base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Set n8n version and release date
        id: set-version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.n8n_version }}" ]; then
            echo "N8N_VERSION=${{ github.event.inputs.n8n_version }}" >> $GITHUB_ENV
          else
            echo "N8N_VERSION=1.81.0" >> $GITHUB_ENV
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.node_version }}" ]; then
            echo "NODE_VERSION=${{ github.event.inputs.node_version }}" >> $GITHUB_ENV
          else
            echo "NODE_VERSION=22" >> $GITHUB_ENV
          fi
          echo "RELEASE_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Build n8n image
        run: |
          cd ./docker/images/n8n
          docker build -t registry.digitalocean.com/replikate-sg/n8n:${{ env.SHORT_SHA }} \
            --build-arg NODE_VERSION=${{ env.NODE_VERSION }} \
            --build-arg N8N_VERSION=${{ env.N8N_VERSION }} \
            --build-arg N8N_RELEASE_DATE=${{ env.RELEASE_DATE }} \
            .

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/replikate-sg/n8n:${{ env.SHORT_SHA }}
