name: Build and Push n8n Docker Image

on:
  push:
    branches: [ replikate ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Build container image
        run: docker build -t registry.digitalocean.com/replikate-sg/n8n:$(echo $GITHUB_SHA | head -c7) -f ./docker/images/n8n-base/Dockerfile .

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/replikate-sg/n8n:$(echo $GITHUB_SHA | head -c7)
